version: '3.8'

services:
  postgresdb: 
    image: postgres:11
    environment:
      POSTGRES_USER: avenger
      POSTGRES_PASSWORD: avengerpass
    restart: always

  webpacker:
    image: ${DOCKER_IMAGE_NAME-rumandcode_challenge}
    command: ["./scripts/start_webpack_dev.sh"]
    volumes:
      - .:/app
    ports:
      - 3035:3035

  app:
    image: ${DOCKER_IMAGE_NAME-rumandcode_challenge}
    build:
      context: .
      args:
        precompileassets: "not"
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "./scripts/start_rails.sh"]
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    links:
      - postgresdb
    ports:
      - '3000:3000'